// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZagrebEvents.DAL;

#nullable disable

namespace ZagrebEvents.DAL.Migrations
{
    [DbContext(typeof(ZagrebEventsDbContext))]
    partial class ZagrebEventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserFavoriteVenue", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("UserFavoriteVenue");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            UserId = 1,
                            VenueId = 3
                        },
                        new
                        {
                            UserId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            UserId = 4,
                            VenueId = 2
                        },
                        new
                        {
                            UserId = 4,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeLimit = 18,
                            Description = "Najbolja techno večer u gradu s rezidentnim DJ-em MLADY koji dolazi direktno iz Berlina.",
                            EndTime = new DateTime(2026, 4, 26, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 15.00m,
                            Name = "Techno Night ft. MLADY",
                            PosterUrl = "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600",
                            StartTime = new DateTime(2026, 4, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeLimit = 18,
                            Description = "Vojko V dolazi u Club Culture na ekskluzivni nastup! Jedna od najpopularnijih domaćih glazbenih zvezda.",
                            EndTime = new DateTime(2026, 5, 13, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 25.00m,
                            Name = "Vojko V Live",
                            PosterUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600",
                            StartTime = new DateTime(2026, 5, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            AgeLimit = 18,
                            Description = "Vratite se u 90-te uz najbolje hitove!",
                            EndTime = new DateTime(2026, 3, 16, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 10.00m,
                            Name = "Retro Party 90s",
                            PosterUrl = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600",
                            StartTime = new DateTime(2026, 3, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            AgeLimit = 0,
                            Description = "Testiraj svoje znanje svaku srijedu! Nagrada za 1. mjesto.",
                            EndTime = new DateTime(2026, 4, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Pub Quiz Srijeda",
                            PosterUrl = "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600",
                            StartTime = new DateTime(2026, 4, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            AgeLimit = 0,
                            Description = "Akustični nastupi lokalnih bendova uz craft pivo.",
                            EndTime = new DateTime(2026, 5, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 5.00m,
                            Name = "Acoustic Night - Lokalni bendovi",
                            PosterUrl = "https://images.unsplash.com/photo-1511735111819-9a3efd16269a?w=600",
                            StartTime = new DateTime(2026, 5, 9, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 6,
                            AgeLimit = 0,
                            Description = "Specijalni pub quiz o filmovima.",
                            EndTime = new DateTime(2026, 3, 19, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Pub Quiz - Filmska Tematika",
                            PosterUrl = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600",
                            StartTime = new DateTime(2026, 3, 19, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            AgeLimit = 18,
                            Description = "Dvodnevni festival elektronske glazbe na Bundeku s top europskim DJ-evima.",
                            EndTime = new DateTime(2026, 6, 22, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 50.00m,
                            Name = "Zagreb Summer Beats",
                            PosterUrl = "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600",
                            StartTime = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 8,
                            AgeLimit = 0,
                            Description = "Legendarni Let 3 na pozornici Bundek!",
                            EndTime = new DateTime(2026, 5, 10, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 20.00m,
                            Name = "Let 3 - Bundek Open Air",
                            PosterUrl = "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600",
                            StartTime = new DateTime(2026, 5, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 9,
                            AgeLimit = 16,
                            Description = "Proljetni mini-festival s lokalnim DJ-evima.",
                            EndTime = new DateTime(2026, 3, 22, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 15.00m,
                            Name = "Spring Vibes Festival",
                            PosterUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600",
                            StartTime = new DateTime(2026, 3, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.PriceListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("PriceListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Piće",
                            ItemName = "Gin & Tonic",
                            Price = 8.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Piće",
                            ItemName = "Vodka Red Bull",
                            Price = 9.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Piće",
                            ItemName = "Jack & Coke",
                            Price = 10.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Piće",
                            ItemName = "Heineken 0.5l",
                            Price = 5.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ulaznica",
                            ItemName = "VIP ulaz",
                            Price = 30.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Piće",
                            ItemName = "Espresso",
                            Price = 1.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Piće",
                            ItemName = "Cappuccino",
                            Price = 2.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Piće",
                            ItemName = "Craft pivo",
                            Price = 5.00m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Hrana",
                            ItemName = "Sendvič",
                            Price = 4.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "Piće",
                            ItemName = "Pivo 0.5l",
                            Price = 4.00m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Piće",
                            ItemName = "Kokteli",
                            Price = 7.00m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Hrana",
                            ItemName = "Pizza komad",
                            Price = 3.50m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Ulaznica",
                            ItemName = "Festival pass",
                            Price = 50.00m,
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumSpending")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            MinimumSpending = 100.00m,
                            Note = "Rođendan, molimo balon dekoraciju",
                            NumberOfGuests = 4,
                            Status = 1,
                            TableId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            MinimumSpending = 150.00m,
                            Note = "",
                            NumberOfGuests = 6,
                            Status = 0,
                            TableId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 4,
                            MinimumSpending = 0.00m,
                            Note = "Blizu pozornice ako je moguće",
                            NumberOfGuests = 3,
                            Status = 1,
                            TableId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 7,
                            MinimumSpending = 200.00m,
                            Note = "Otkazano zbog bolesti",
                            NumberOfGuests = 5,
                            Status = 2,
                            TableId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 8,
                            MinimumSpending = 0.00m,
                            Note = "",
                            NumberOfGuests = 4,
                            Status = 1,
                            TableId = 10,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Odlična atmosfera, DJ je bio fenomenalan!",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Super quiz, pitanja su bila zanimljiva.",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 6,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Bilo je OK, ali predugo čekanje za piće.",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Rating = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Najbolji festival ove godine, 10/10!",
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 9,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Dobar vibe, lokacija predivna.",
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 9,
                            Rating = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 1,
                            Zone = 0
                        },
                        new
                        {
                            Id = 2,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 1,
                            Zone = 1
                        },
                        new
                        {
                            Id = 3,
                            SeatCount = 8,
                            TableNumber = 3,
                            VenueId = 1,
                            Zone = 1
                        },
                        new
                        {
                            Id = 4,
                            SeatCount = 4,
                            TableNumber = 4,
                            VenueId = 1,
                            Zone = 0
                        },
                        new
                        {
                            Id = 5,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 6,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 7,
                            SeatCount = 4,
                            TableNumber = 3,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 8,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 3,
                            Zone = 1
                        },
                        new
                        {
                            Id = 9,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 3,
                            Zone = 1
                        },
                        new
                        {
                            Id = 10,
                            SeatCount = 4,
                            TableNumber = 3,
                            VenueId = 3,
                            Zone = 0
                        },
                        new
                        {
                            Id = 11,
                            SeatCount = 4,
                            TableNumber = 4,
                            VenueId = 3,
                            Zone = 0
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan.golubic@email.com",
                            FirstName = "Ivan",
                            LastName = "Golubić",
                            PhoneNumber = "+385911234567",
                            RegisteredAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.horvat@email.com",
                            FirstName = "Ana",
                            LastName = "Horvat",
                            PhoneNumber = "+385917654321",
                            RegisteredAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.kovacevic@email.com",
                            FirstName = "Marko",
                            LastName = "Kovačević",
                            PhoneNumber = "+385921112233",
                            RegisteredAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2000, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.babic@email.com",
                            FirstName = "Petra",
                            LastName = "Babić",
                            PhoneNumber = "+385998887766",
                            RegisteredAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1985, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka.peric@admin.com",
                            FirstName = "Luka",
                            LastName = "Perić",
                            PhoneNumber = "+385915556677",
                            RegisteredAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 2
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2010, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karlo.novak@email.com",
                            FirstName = "Karlo",
                            LastName = "Novak",
                            PhoneNumber = "+385912223344",
                            RegisteredAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jabukovac 10, Zagreb",
                            Capacity = 500,
                            ContactPhone = "+38514567890",
                            Description = "Najpoznatiji noćni klub u Zagrebu s vrhunskim DJ programom.",
                            ImageUrl = "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800",
                            Latitude = 45.814399999999999,
                            Longitude = 15.9786,
                            Name = "Club Culture",
                            Type = 0,
                            WorkingHours = "22:00 - 05:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ilica 45, Zagreb",
                            Capacity = 80,
                            ContactPhone = "+38511234567",
                            Description = "Ugodan kafić u centru Zagreba s pub kviz večerima.",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
                            Latitude = 45.813099999999999,
                            Longitude = 15.9665,
                            Name = "Kavana Lav",
                            Type = 2,
                            WorkingHours = "08:00 - 23:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bundek, Novi Zagreb",
                            Capacity = 5000,
                            ContactPhone = "+38519876543",
                            Description = "Open-air pozornica pored jezera Bundek za festivale i koncerte.",
                            ImageUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800",
                            Latitude = 45.786900000000003,
                            Longitude = 15.987399999999999,
                            Name = "Park Stage Bundek",
                            Type = 3,
                            WorkingHours = "16:00 - 02:00"
                        });
                });

            modelBuilder.Entity("UserFavoriteVenue", b =>
                {
                    b.HasOne("ZagrebEvents.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.PriceListItem", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("PriceList")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Reservation", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Event", "Event")
                        .WithMany("Reservations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Review", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Event", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("Tables")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ZagrebEvents.Model.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PriceList");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
