// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZagrebEvents.DAL;

#nullable disable

namespace ZagrebEvents.DAL.Migrations
{
    [DbContext(typeof(ZagrebEventsDbContext))]
    [Migration("20260607145325_SeedRealZagrebVenues")]
    partial class SeedRealZagrebVenues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserFavoriteVenue", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("UserFavoriteVenue");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            UserId = 1,
                            VenueId = 3
                        },
                        new
                        {
                            UserId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            UserId = 4,
                            VenueId = 2
                        },
                        new
                        {
                            UserId = 4,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ZagrebEvents.Model.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeLimit = 18,
                            Description = "Najbolja techno večer u gradu s rezidentnim DJ-em MLADY koji dolazi direktno iz Berlina.",
                            EndTime = new DateTime(2026, 4, 26, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 15.00m,
                            Name = "Techno Night ft. MLADY",
                            PosterUrl = "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600",
                            StartTime = new DateTime(2026, 4, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeLimit = 18,
                            Description = "Vojko V dolazi u Club Culture na ekskluzivni nastup! Jedna od najpopularnijih domaćih glazbenih zvezda.",
                            EndTime = new DateTime(2026, 5, 13, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 25.00m,
                            Name = "Vojko V Live",
                            PosterUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600",
                            StartTime = new DateTime(2026, 5, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            AgeLimit = 18,
                            Description = "Vratite se u 90-te uz najbolje hitove!",
                            EndTime = new DateTime(2026, 3, 16, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 10.00m,
                            Name = "Retro Party 90s",
                            PosterUrl = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600",
                            StartTime = new DateTime(2026, 3, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            AgeLimit = 0,
                            Description = "Testiraj svoje znanje svaku srijedu! Nagrada za 1. mjesto.",
                            EndTime = new DateTime(2026, 4, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Pub Quiz Srijeda",
                            PosterUrl = "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600",
                            StartTime = new DateTime(2026, 4, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            AgeLimit = 0,
                            Description = "Akustični nastupi lokalnih bendova uz craft pivo.",
                            EndTime = new DateTime(2026, 5, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 5.00m,
                            Name = "Acoustic Night - Lokalni bendovi",
                            PosterUrl = "https://images.unsplash.com/photo-1511735111819-9a3efd16269a?w=600",
                            StartTime = new DateTime(2026, 5, 9, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 6,
                            AgeLimit = 0,
                            Description = "Specijalni pub quiz o filmovima.",
                            EndTime = new DateTime(2026, 3, 19, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Pub Quiz - Filmska Tematika",
                            PosterUrl = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600",
                            StartTime = new DateTime(2026, 3, 19, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            AgeLimit = 18,
                            Description = "Dvodnevni festival elektronske glazbe na Bundeku s top europskim DJ-evima.",
                            EndTime = new DateTime(2026, 6, 22, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 50.00m,
                            Name = "Zagreb Summer Beats",
                            PosterUrl = "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600",
                            StartTime = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 8,
                            AgeLimit = 0,
                            Description = "Legendarni Let 3 na pozornici Bundek!",
                            EndTime = new DateTime(2026, 5, 10, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 20.00m,
                            Name = "Let 3 - Bundek Open Air",
                            PosterUrl = "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600",
                            StartTime = new DateTime(2026, 5, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 9,
                            AgeLimit = 16,
                            Description = "Proljetni mini-festival s lokalnim DJ-evima.",
                            EndTime = new DateTime(2026, 3, 22, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 15.00m,
                            Name = "Spring Vibes Festival",
                            PosterUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600",
                            StartTime = new DateTime(2026, 3, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 10,
                            AgeLimit = 18,
                            Description = "Veliko otvorenje ljetne sezone na Jarunu uz top elektronske DJ-eve.",
                            EndTime = new DateTime(2026, 6, 21, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 20.00m,
                            Name = "Aquarius Summer Opening",
                            PosterUrl = "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600",
                            StartTime = new DateTime(2026, 6, 20, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 11,
                            AgeLimit = 16,
                            Description = "Legendarni zagrebački bend uživo u Boogaloou.",
                            EndTime = new DateTime(2026, 7, 5, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 25.00m,
                            Name = "Hladno Pivo Live",
                            PosterUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600",
                            StartTime = new DateTime(2026, 7, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 12,
                            AgeLimit = 18,
                            Description = "Noć techno glazbe s rezidentnim i gostujućim DJ-evima.",
                            EndTime = new DateTime(2026, 6, 20, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 15.00m,
                            Name = "Tvornica Techno Night",
                            PosterUrl = "https://images.unsplash.com/photo-1545128485-c400e7702796?w=600",
                            StartTime = new DateTime(2026, 6, 19, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 13,
                            AgeLimit = 16,
                            Description = "Underground punk i rock bendovi u Močvari.",
                            EndTime = new DateTime(2026, 6, 22, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 10.00m,
                            Name = "Punk Rock Večer",
                            PosterUrl = "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600",
                            StartTime = new DateTime(2026, 6, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 14,
                            AgeLimit = 0,
                            Description = "Akustični i indie nastupi u Vintage Industrial baru.",
                            EndTime = new DateTime(2026, 6, 18, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 8.00m,
                            Name = "Indie Live Session",
                            PosterUrl = "https://images.unsplash.com/photo-1511735111819-9a3efd16269a?w=600",
                            StartTime = new DateTime(2026, 6, 18, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 8
                        },
                        new
                        {
                            Id = 15,
                            AgeLimit = 18,
                            Description = "Cijela noć techna u industrijskom ambijentu Katrana.",
                            EndTime = new DateTime(2026, 6, 28, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 18.00m,
                            Name = "Katran Underground: Techno",
                            PosterUrl = "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600",
                            StartTime = new DateTime(2026, 6, 27, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 9
                        },
                        new
                        {
                            Id = 16,
                            AgeLimit = 18,
                            Description = "Najbolji house DJ-evi grada na jednom mjestu.",
                            EndTime = new DateTime(2026, 7, 6, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 16.00m,
                            Name = "House Nation",
                            PosterUrl = "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600",
                            StartTime = new DateTime(2026, 7, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 10
                        },
                        new
                        {
                            Id = 17,
                            AgeLimit = 18,
                            Description = "Subotnja party noć s komercijalnim hitovima.",
                            EndTime = new DateTime(2026, 6, 29, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 12.00m,
                            Name = "Opera Saturday",
                            PosterUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600",
                            StartTime = new DateTime(2026, 6, 28, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 11
                        },
                        new
                        {
                            Id = 18,
                            AgeLimit = 18,
                            Description = "R'n'B i hip-hop klasici cijelu noć.",
                            EndTime = new DateTime(2026, 7, 12, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 14.00m,
                            Name = "Masters R'n'B Night",
                            PosterUrl = "https://images.unsplash.com/photo-1438557068880-c5f474830377?w=600",
                            StartTime = new DateTime(2026, 7, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 12
                        },
                        new
                        {
                            Id = 19,
                            AgeLimit = 0,
                            Description = "Opušteni akustični nastup u srcu Tkalče.",
                            EndTime = new DateTime(2026, 6, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Pločnik Acoustic",
                            PosterUrl = "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600",
                            StartTime = new DateTime(2026, 6, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 13
                        },
                        new
                        {
                            Id = 20,
                            AgeLimit = 18,
                            Description = "Industrijski rave s europskim techno headlinerima.",
                            EndTime = new DateTime(2026, 7, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 22.00m,
                            Name = "Hangar Rave",
                            PosterUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600",
                            StartTime = new DateTime(2026, 7, 12, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 14
                        },
                        new
                        {
                            Id = 21,
                            AgeLimit = 0,
                            Description = "Nezavisni bendovi i izvođači u Pogonu.",
                            EndTime = new DateTime(2026, 6, 27, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 7.00m,
                            Name = "Alternativna Scena",
                            PosterUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=600",
                            StartTime = new DateTime(2026, 6, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 15
                        },
                        new
                        {
                            Id = 22,
                            AgeLimit = 18,
                            Description = "Spoj umjetničke izložbe i DJ seta u Laubi.",
                            EndTime = new DateTime(2026, 7, 4, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 10.00m,
                            Name = "Art & Beats",
                            PosterUrl = "https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=600",
                            StartTime = new DateTime(2026, 7, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 16
                        },
                        new
                        {
                            Id = 23,
                            AgeLimit = 0,
                            Description = "Veliki koncert Gibonnija u Domu sportova.",
                            EndTime = new DateTime(2026, 9, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 35.00m,
                            Name = "Gibonni Live",
                            PosterUrl = "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600",
                            StartTime = new DateTime(2026, 9, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 17
                        },
                        new
                        {
                            Id = 24,
                            AgeLimit = 0,
                            Description = "Veliki pop spektakl u Areni Zagreb.",
                            EndTime = new DateTime(2026, 9, 20, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 40.00m,
                            Name = "Severina Spektakl",
                            PosterUrl = "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600",
                            StartTime = new DateTime(2026, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 18
                        },
                        new
                        {
                            Id = 25,
                            AgeLimit = 0,
                            Description = "Večer klasične glazbe u dvorani Lisinski.",
                            EndTime = new DateTime(2026, 6, 30, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 28.00m,
                            Name = "Zagrebačka Filharmonija",
                            PosterUrl = "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600",
                            StartTime = new DateTime(2026, 6, 30, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 19
                        },
                        new
                        {
                            Id = 26,
                            AgeLimit = 16,
                            Description = "Najveći hrvatski open-air glazbeni festival na Jarunu.",
                            EndTime = new DateTime(2026, 6, 25, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 89.00m,
                            Name = "INmusic Festival",
                            PosterUrl = "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600",
                            StartTime = new DateTime(2026, 6, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 20
                        },
                        new
                        {
                            Id = 27,
                            AgeLimit = 16,
                            Description = "Cjelodnevni open-air festival u parku Maksimir.",
                            EndTime = new DateTime(2026, 7, 19, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 30.00m,
                            Name = "Maksimir Open Air",
                            PosterUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600",
                            StartTime = new DateTime(2026, 7, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            VenueId = 21
                        },
                        new
                        {
                            Id = 28,
                            AgeLimit = 18,
                            Description = "Ljetne DJ večeri pod zvijezdama na Šalati.",
                            EndTime = new DateTime(2026, 7, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 12.00m,
                            Name = "Šalata Summer Sessions",
                            PosterUrl = "https://images.unsplash.com/photo-1492011221367-f47e3ccd77a0?w=600",
                            StartTime = new DateTime(2026, 7, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 22
                        },
                        new
                        {
                            Id = 29,
                            AgeLimit = 0,
                            Description = "Opuštene DJ večeri u parku Ribnjak.",
                            EndTime = new DateTime(2026, 6, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Ribnjak Chill Sessions",
                            PosterUrl = "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=600",
                            StartTime = new DateTime(2026, 6, 17, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 23
                        },
                        new
                        {
                            Id = 30,
                            AgeLimit = 0,
                            Description = "Jutarnji jazz uz vrhunsku kavu u Eli's Caffeu.",
                            EndTime = new DateTime(2026, 6, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Coffee & Jazz",
                            PosterUrl = "https://images.unsplash.com/photo-1511735111819-9a3efd16269a?w=600",
                            StartTime = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            VenueId = 24
                        },
                        new
                        {
                            Id = 31,
                            AgeLimit = 18,
                            Description = "Cjelonoćni techno maraton u Club Cultureu.",
                            EndTime = new DateTime(2026, 7, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 18.00m,
                            Name = "Summer Techno Marathon",
                            PosterUrl = "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600",
                            StartTime = new DateTime(2026, 7, 19, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 32,
                            AgeLimit = 0,
                            Description = "Tjedni pub kviz u Kavani Lav, ljetno izdanje.",
                            EndTime = new DateTime(2026, 6, 24, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryPrice = 0.00m,
                            Name = "Ljetni Pub Quiz",
                            PosterUrl = "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600",
                            StartTime = new DateTime(2026, 6, 24, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.PriceListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("PriceListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Piće",
                            ItemName = "Gin & Tonic",
                            Price = 8.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Piće",
                            ItemName = "Vodka Red Bull",
                            Price = 9.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Piće",
                            ItemName = "Jack & Coke",
                            Price = 10.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Piće",
                            ItemName = "Heineken 0.5l",
                            Price = 5.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ulaznica",
                            ItemName = "VIP ulaz",
                            Price = 30.00m,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Piće",
                            ItemName = "Espresso",
                            Price = 1.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Piće",
                            ItemName = "Cappuccino",
                            Price = 2.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Piće",
                            ItemName = "Craft pivo",
                            Price = 5.00m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Hrana",
                            ItemName = "Sendvič",
                            Price = 4.50m,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "Piće",
                            ItemName = "Pivo 0.5l",
                            Price = 4.00m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Piće",
                            ItemName = "Kokteli",
                            Price = 7.00m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Hrana",
                            ItemName = "Pizza komad",
                            Price = 3.50m,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Ulaznica",
                            ItemName = "Festival pass",
                            Price = 50.00m,
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumSpending")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            MinimumSpending = 100.00m,
                            Note = "Rođendan, molimo balon dekoraciju",
                            NumberOfGuests = 4,
                            Status = 1,
                            TableId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            MinimumSpending = 150.00m,
                            Note = "",
                            NumberOfGuests = 6,
                            Status = 0,
                            TableId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 4,
                            MinimumSpending = 0.00m,
                            Note = "Blizu pozornice ako je moguće",
                            NumberOfGuests = 3,
                            Status = 1,
                            TableId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 7,
                            MinimumSpending = 200.00m,
                            Note = "Otkazano zbog bolesti",
                            NumberOfGuests = 5,
                            Status = 2,
                            TableId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 8,
                            MinimumSpending = 0.00m,
                            Note = "",
                            NumberOfGuests = 4,
                            Status = 1,
                            TableId = 10,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Odlična atmosfera, DJ je bio fenomenalan!",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Super quiz, pitanja su bila zanimljiva.",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 6,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Bilo je OK, ali predugo čekanje za piće.",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Rating = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Najbolji festival ove godine, 10/10!",
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 9,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Dobar vibe, lokacija predivna.",
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 9,
                            Rating = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 1,
                            Zone = 0
                        },
                        new
                        {
                            Id = 2,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 1,
                            Zone = 1
                        },
                        new
                        {
                            Id = 3,
                            SeatCount = 8,
                            TableNumber = 3,
                            VenueId = 1,
                            Zone = 1
                        },
                        new
                        {
                            Id = 4,
                            SeatCount = 4,
                            TableNumber = 4,
                            VenueId = 1,
                            Zone = 0
                        },
                        new
                        {
                            Id = 5,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 6,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 7,
                            SeatCount = 4,
                            TableNumber = 3,
                            VenueId = 2,
                            Zone = 0
                        },
                        new
                        {
                            Id = 8,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 3,
                            Zone = 1
                        },
                        new
                        {
                            Id = 9,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 3,
                            Zone = 1
                        },
                        new
                        {
                            Id = 10,
                            SeatCount = 4,
                            TableNumber = 3,
                            VenueId = 3,
                            Zone = 0
                        },
                        new
                        {
                            Id = 11,
                            SeatCount = 4,
                            TableNumber = 4,
                            VenueId = 3,
                            Zone = 0
                        },
                        new
                        {
                            Id = 12,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 4,
                            Zone = 1
                        },
                        new
                        {
                            Id = 13,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 4,
                            Zone = 0
                        },
                        new
                        {
                            Id = 14,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 5,
                            Zone = 1
                        },
                        new
                        {
                            Id = 15,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 5,
                            Zone = 0
                        },
                        new
                        {
                            Id = 16,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 6,
                            Zone = 1
                        },
                        new
                        {
                            Id = 17,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 6,
                            Zone = 0
                        },
                        new
                        {
                            Id = 18,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 7,
                            Zone = 0
                        },
                        new
                        {
                            Id = 19,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 7,
                            Zone = 0
                        },
                        new
                        {
                            Id = 20,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 8,
                            Zone = 0
                        },
                        new
                        {
                            Id = 21,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 8,
                            Zone = 1
                        },
                        new
                        {
                            Id = 22,
                            SeatCount = 8,
                            TableNumber = 1,
                            VenueId = 9,
                            Zone = 1
                        },
                        new
                        {
                            Id = 23,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 9,
                            Zone = 0
                        },
                        new
                        {
                            Id = 24,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 10,
                            Zone = 1
                        },
                        new
                        {
                            Id = 25,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 10,
                            Zone = 0
                        },
                        new
                        {
                            Id = 26,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 11,
                            Zone = 1
                        },
                        new
                        {
                            Id = 27,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 11,
                            Zone = 0
                        },
                        new
                        {
                            Id = 28,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 12,
                            Zone = 1
                        },
                        new
                        {
                            Id = 29,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 12,
                            Zone = 0
                        },
                        new
                        {
                            Id = 30,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 13,
                            Zone = 0
                        },
                        new
                        {
                            Id = 31,
                            SeatCount = 2,
                            TableNumber = 2,
                            VenueId = 13,
                            Zone = 0
                        },
                        new
                        {
                            Id = 32,
                            SeatCount = 8,
                            TableNumber = 1,
                            VenueId = 14,
                            Zone = 1
                        },
                        new
                        {
                            Id = 33,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 14,
                            Zone = 0
                        },
                        new
                        {
                            Id = 34,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 15,
                            Zone = 0
                        },
                        new
                        {
                            Id = 35,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 15,
                            Zone = 0
                        },
                        new
                        {
                            Id = 36,
                            SeatCount = 6,
                            TableNumber = 1,
                            VenueId = 16,
                            Zone = 1
                        },
                        new
                        {
                            Id = 37,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 16,
                            Zone = 0
                        },
                        new
                        {
                            Id = 38,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 20,
                            Zone = 0
                        },
                        new
                        {
                            Id = 39,
                            SeatCount = 6,
                            TableNumber = 2,
                            VenueId = 20,
                            Zone = 1
                        },
                        new
                        {
                            Id = 40,
                            SeatCount = 4,
                            TableNumber = 1,
                            VenueId = 22,
                            Zone = 0
                        },
                        new
                        {
                            Id = 41,
                            SeatCount = 4,
                            TableNumber = 2,
                            VenueId = 22,
                            Zone = 0
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan.golubic@email.com",
                            FirstName = "Ivan",
                            LastName = "Golubić",
                            PhoneNumber = "+385911234567",
                            RegisteredAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.horvat@email.com",
                            FirstName = "Ana",
                            LastName = "Horvat",
                            PhoneNumber = "+385917654321",
                            RegisteredAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.kovacevic@email.com",
                            FirstName = "Marko",
                            LastName = "Kovačević",
                            PhoneNumber = "+385921112233",
                            RegisteredAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2000, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.babic@email.com",
                            FirstName = "Petra",
                            LastName = "Babić",
                            PhoneNumber = "+385998887766",
                            RegisteredAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1985, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka.peric@admin.com",
                            FirstName = "Luka",
                            LastName = "Perić",
                            PhoneNumber = "+385915556677",
                            RegisteredAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 2
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2010, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karlo.novak@email.com",
                            FirstName = "Karlo",
                            LastName = "Novak",
                            PhoneNumber = "+385912223344",
                            RegisteredAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        });
                });

            modelBuilder.Entity("ZagrebEvents.Model.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerAppUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jabukovac 10, Zagreb",
                            Capacity = 500,
                            ContactPhone = "+38514567890",
                            Description = "Najpoznatiji noćni klub u Zagrebu s vrhunskim DJ programom.",
                            ImageUrl = "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800",
                            Latitude = 45.814399999999999,
                            Longitude = 15.9786,
                            Name = "Club Culture",
                            Type = 0,
                            WorkingHours = "22:00 - 05:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ilica 45, Zagreb",
                            Capacity = 80,
                            ContactPhone = "+38511234567",
                            Description = "Ugodan kafić u centru Zagreba s pub kviz večerima.",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
                            Latitude = 45.813099999999999,
                            Longitude = 15.9665,
                            Name = "Kavana Lav",
                            Type = 2,
                            WorkingHours = "08:00 - 23:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bundek, Novi Zagreb",
                            Capacity = 5000,
                            ContactPhone = "+38519876543",
                            Description = "Open-air pozornica pored jezera Bundek za festivale i koncerte.",
                            ImageUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800",
                            Latitude = 45.786900000000003,
                            Longitude = 15.987399999999999,
                            Name = "Park Stage Bundek",
                            Type = 3,
                            WorkingHours = "16:00 - 02:00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Aleja Matije Ljubeka 2a, Jarun",
                            Capacity = 1500,
                            ContactPhone = "+38513640231",
                            Description = "Legendarni klub na jezeru Jarun, dom elektronske glazbe u Zagrebu.",
                            ImageUrl = "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800",
                            Latitude = 45.783299999999997,
                            Longitude = 15.918100000000001,
                            Name = "Aquarius",
                            Type = 0,
                            WorkingHours = "23:00 - 06:00"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ulica grada Vukovara 68",
                            Capacity = 1200,
                            ContactPhone = "+38516313021",
                            Description = "Klub i koncertni prostor za domaće i strane izvođače.",
                            ImageUrl = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800",
                            Latitude = 45.801299999999998,
                            Longitude = 15.9869,
                            Name = "Boogaloo",
                            Type = 0,
                            WorkingHours = "21:00 - 04:00"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Šubićeva 2",
                            Capacity = 1000,
                            ContactPhone = "+38514606650",
                            Description = "Koncertni i klupski prostor s bogatim programom uživo.",
                            ImageUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
                            Latitude = 45.814599999999999,
                            Longitude = 16.000800000000002,
                            Name = "Tvornica Kulture",
                            Type = 0,
                            WorkingHours = "20:00 - 04:00"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Trnjanski nasip bb",
                            Capacity = 600,
                            ContactPhone = "+38516154290",
                            Description = "Alternativni klub uz Savu, dom rock i underground scene.",
                            ImageUrl = "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800",
                            Latitude = 45.795000000000002,
                            Longitude = 15.976000000000001,
                            Name = "Klub Močvara",
                            Type = 0,
                            WorkingHours = "20:00 - 03:00"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Savska cesta 160",
                            Capacity = 400,
                            ContactPhone = "+38598123456",
                            Description = "Industrijski bar s koncertima indie i rock bendova.",
                            ImageUrl = "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800",
                            Latitude = 45.789999999999999,
                            Longitude = 15.962999999999999,
                            Name = "Vintage Industrial Bar",
                            Type = 1,
                            WorkingHours = "19:00 - 02:00"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Radnička cesta 27",
                            Capacity = 800,
                            ContactPhone = "+38591222333",
                            Description = "Underground techno prostor u bivšoj tvornici.",
                            ImageUrl = "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800",
                            Latitude = 45.802999999999997,
                            Longitude = 16.015000000000001,
                            Name = "Katran",
                            Type = 0,
                            WorkingHours = "23:00 - 07:00"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Radnička cesta 21",
                            Capacity = 700,
                            ContactPhone = "+38591444555",
                            Description = "House i techno klub s vrhunskim sound systemom.",
                            ImageUrl = "https://images.unsplash.com/photo-1545128485-c400e7702796?w=800",
                            Latitude = 45.804000000000002,
                            Longitude = 16.012,
                            Name = "Sirup Club",
                            Type = 0,
                            WorkingHours = "23:00 - 06:00"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Savska cesta 141",
                            Capacity = 900,
                            ContactPhone = "+38591666777",
                            Description = "Mainstream klub s komercijalnim hitovima i gostujućim DJ-evima.",
                            ImageUrl = "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
                            Latitude = 45.787999999999997,
                            Longitude = 15.965,
                            Name = "Opera Club",
                            Type = 0,
                            WorkingHours = "23:00 - 05:00"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Trg Krešimira Ćosića 9",
                            Capacity = 500,
                            ContactPhone = "+38591888999",
                            Description = "R'n'B i hip-hop klub u centru grada.",
                            ImageUrl = "https://images.unsplash.com/photo-1438557068880-c5f474830377?w=800",
                            Latitude = 45.798999999999999,
                            Longitude = 15.970000000000001,
                            Name = "Masters Club",
                            Type = 0,
                            WorkingHours = "22:00 - 05:00"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tkalčićeva 41",
                            Capacity = 200,
                            ContactPhone = "+38591101010",
                            Description = "Popularni bar u Tkalči s DJ programom vikendom.",
                            ImageUrl = "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800",
                            Latitude = 45.814999999999998,
                            Longitude = 15.976000000000001,
                            Name = "Pločnik",
                            Type = 1,
                            WorkingHours = "08:00 - 24:00"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Trnjanska cesta",
                            Capacity = 1000,
                            ContactPhone = "+38591202020",
                            Description = "Veliki techno prostor za rave partyje.",
                            ImageUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800",
                            Latitude = 45.789999999999999,
                            Longitude = 15.99,
                            Name = "Hangar",
                            Type = 0,
                            WorkingHours = "23:00 - 08:00"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Trnjanski nasip 23",
                            Capacity = 600,
                            ContactPhone = "+38591303030",
                            Description = "Prostor za alternativnu i nezavisnu kulturu.",
                            ImageUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800",
                            Latitude = 45.792999999999999,
                            Longitude = 15.978,
                            Name = "Pogon Jedinstvo",
                            Type = 0,
                            WorkingHours = "20:00 - 04:00"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Baruna Filipovića 23a",
                            Capacity = 350,
                            ContactPhone = "+38516323165",
                            Description = "Prostor za umjetnost i događanja u bivšoj tvorničkoj hali.",
                            ImageUrl = "https://images.unsplash.com/photo-1504333638930-c8787321eee0?w=800",
                            Latitude = 45.811999999999998,
                            Longitude = 15.945,
                            Name = "Lauba",
                            Type = 1,
                            WorkingHours = "11:00 - 24:00"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Trg Krešimira Ćosića 11",
                            Capacity = 6000,
                            ContactPhone = "+38513650333",
                            Description = "Dvorana za velike koncerte i događanja.",
                            ImageUrl = "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800",
                            Latitude = 45.805999999999997,
                            Longitude = 15.954000000000001,
                            Name = "Dom Sportova",
                            Type = 0,
                            WorkingHours = "po programu"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Vice Vukova 8",
                            Capacity = 15000,
                            ContactPhone = "+38516121111",
                            Description = "Najveća koncertna arena u Zagrebu.",
                            ImageUrl = "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800",
                            Latitude = 45.770000000000003,
                            Longitude = 15.943,
                            Name = "Arena Zagreb",
                            Type = 0,
                            WorkingHours = "po programu"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Trg Stjepana Radića 4",
                            Capacity = 1850,
                            ContactPhone = "+38516121166",
                            Description = "Koncertna dvorana za klasičnu i ozbiljnu glazbu.",
                            ImageUrl = "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800",
                            Latitude = 45.802,
                            Longitude = 15.967000000000001,
                            Name = "KD Vatroslav Lisinski",
                            Type = 0,
                            WorkingHours = "po programu"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Jezero Jarun",
                            Capacity = 50000,
                            ContactPhone = "+38591505050",
                            Description = "Otvoreni prostor uz jezero, domaćin velikih festivala.",
                            ImageUrl = "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800",
                            Latitude = 45.781999999999996,
                            Longitude = 15.914999999999999,
                            Name = "Jarun Plaža",
                            Type = 3,
                            WorkingHours = "open-air"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Maksimirski perivoj",
                            Capacity = 8000,
                            ContactPhone = "+38591606060",
                            Description = "Najveći zagrebački park, domaćin open-air događanja.",
                            ImageUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
                            Latitude = 45.826000000000001,
                            Longitude = 16.018000000000001,
                            Name = "Park Maksimir",
                            Type = 3,
                            WorkingHours = "open-air"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Schrottova ulica",
                            Capacity = 2000,
                            ContactPhone = "+38591707070",
                            Description = "Ljetna pozornica i sportski centar na Šalati.",
                            ImageUrl = "https://images.unsplash.com/photo-1492011221367-f47e3ccd77a0?w=800",
                            Latitude = 45.823,
                            Longitude = 15.984999999999999,
                            Name = "Šalata",
                            Type = 3,
                            WorkingHours = "open-air"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Ribnjak",
                            Capacity = 1500,
                            ContactPhone = "+38591808080",
                            Description = "Gradski park s ljetnim chill događanjima.",
                            ImageUrl = "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800",
                            Latitude = 45.817,
                            Longitude = 15.981,
                            Name = "Park Ribnjak",
                            Type = 3,
                            WorkingHours = "open-air"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Ilica 63",
                            Capacity = 60,
                            ContactPhone = "+38591909090",
                            Description = "Poznata kavana specijalizirana za vrhunsku kavu.",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
                            Latitude = 45.811,
                            Longitude = 15.965,
                            Name = "Eli's Caffe",
                            Type = 2,
                            WorkingHours = "07:00 - 20:00"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZagrebEvents.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZagrebEvents.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZagrebEvents.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserFavoriteVenue", b =>
                {
                    b.HasOne("ZagrebEvents.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZagrebEvents.Model.Attachment", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Event", "Event")
                        .WithMany("Attachments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.PriceListItem", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("PriceList")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Reservation", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Event", "Event")
                        .WithMany("Reservations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Review", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Event", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrebEvents.Model.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.HasOne("ZagrebEvents.Model.Venue", "Venue")
                        .WithMany("Tables")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Event", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ZagrebEvents.Model.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ZagrebEvents.Model.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PriceList");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
